In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver import ActionChains
from selenium.webdriver.common.actions.wheel_input import ScrollOrigin

import time 
import os 
from os.path import exists
import pandas as pd
from datetime import date

In [2]:
# Creacion de folder para data de Chrome
Folder = "Chrome_Driver_Data"
# Parent Directory path
Directorio = "C:\\"
#creacion de la ruta
path_chrome = os.path.join(Directorio, Folder)

CHECK_FOLDER = os.path.isdir(path_chrome)

# If folder doesn't exist, then create it
if not CHECK_FOLDER:
    os.makedirs(path_chrome)

# Definir ubicación del driver

#Definir que driver se va a utilizar 
chromeOptions = webdriver.ChromeOptions()
#Añadir opciones extras
chromeOptions.add_argument("--start-maximized") 
#chromeOptions.add_argument("--window-size=1300,200")
chromeOptions.add_argument("--disable-gpu") 
chromeOptions.add_experimental_option("excludeSwitches", ["enable-logging"]) 
chromeOptions.add_argument("user-data-dir=" + path_chrome) 
chromeOptions.add_argument("--homepage=about:blank")

#Configurar el driver de selenium
driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()), options = chromeOptions)
#self.driver = webdriver.Chrome(options = chromeOptions)

In [3]:
link = "https://app.powerbi.com/groups/818dc071-4e6f-4a15-82e7-99e3c4be355a/permission/report/2/f81d818a-27e1-473e-865d-37565dc30478/directAccess?experience=power-bi"

In [4]:
driver.get(link)
time.sleep(5)

In [5]:
#full tabla
#element = driver.find_element(By.XPATH, '//*[@id="manage-permissions-table-container"]')

In [6]:
#elemento por elemento
#element = driver.find_element(By.XPATH, '//*[@id="artifactContentView"]/div[1]/div[1]')

In [7]:
accesos = []

for i in range(20):
    for i in range(1, 51, 1):
        try:
            element = driver.find_element(By.XPATH, '//*[@id="artifactContentView"]/div[1]/div[{}]'.format(i))
            accesos.append(element.text)
            #print(element.text)
        except:
            print(i)
            break
        
    scroll_origin = ScrollOrigin.from_element(element)
    ActionChains(driver).scroll_from_origin(scroll_origin, 0, 1500).perform()
    time.sleep(1)

22
31
31
31
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30

In [8]:
driver.quit()

In [10]:
accesos_df = pd.DataFrame(accesos)
accesos_df.head()

                                                   0
0  OJ\nOscar Javier Pachon Alvarez\noscar.pachon@...
1  MM\nMonica Marcela Carvajal Cruz\nmonica.carva...
2  FJ\nFernando Jose Moya Amezquita\nfernando.moy...
3  VH\nVictor Hugo Barbosa\nvictor.barbosa@AvalDi...
4  DP\nDavid Pierre Rodriguez Quiroga\npierre.rod...

In [11]:
accesos_df_final = accesos_df[0].str.split("\n", expand = True).copy()

In [12]:
accesos_df_final.head()

,0,1,2,3
0,OJ,Oscar Javier Pachon Alvarez,oscar.pachon@AvalDigitalLabs.com,Read
1,MM,Monica Marcela Carvajal Cruz,monica.carvajal@AvalDigitalLabs.com,"Workspace Admin, All permissions granted"
2,FJ,Fernando Jose Moya Amezquita,fernando.moya@AvalDigitalLabs.com,Read
3,VH,Victor Hugo Barbosa,victor.barbosa@AvalDigitalLabs.com,"Workspace Member, All permissions granted"
4,DP,David Pierre Rodriguez Quiroga,pierre.rodriguez@AvalDigitalLabs.com,"Workspace Member, All permissions granted"

In [13]:
accesos_df_final.rename(columns = {0: "iniciales", 1:"Persona", 2:"Correo", 3:"Permisos"}, inplace=True)

In [14]:
accesos_df_final.drop_duplicates(inplace=True)

In [15]:
accesos_df_final.head()

,iniciales,Persona,Correo,Permisos
0,OJ,Oscar Javier Pachon Alvarez,oscar.pachon@AvalDigitalLabs.com,Read
1,MM,Monica Marcela Carvajal Cruz,monica.carvajal@AvalDigitalLabs.com,"Workspace Admin, All permissions granted"
2,FJ,Fernando Jose Moya Amezquita,fernando.moya@AvalDigitalLabs.com,Read
3,VH,Victor Hugo Barbosa,victor.barbosa@AvalDigitalLabs.com,"Workspace Member, All permissions granted"
4,DP,David Pierre Rodriguez Quiroga,pierre.rodriguez@AvalDigitalLabs.com,"Workspace Member, All permissions granted"

In [ ]:
tablero = ""

In [16]:
accesos_df_final.to_excel("Accesos " + tablero + " " + str(date.today()) +".xlsx")