In [52]:
import pandas as pd
from natsort import natsorted
import glob
from datetime import date

In [53]:
file_path = "D:\\Documents\\Cristian\\Proyectos varios\\Proyectos Python\\Web Scrapping\\Usuarios PBI\\"

file_paths = natsorted(glob.glob(file_path + "*accesos BPOP*.xlsx", recursive=True))

In [54]:
df = pd.DataFrame()

for f in file_paths:
    #print(f)
    accesos = pd.read_excel(f, 'Sheet1')
    #print(accesos.columns)
    df = pd.concat([df, accesos], ignore_index = True)

In [55]:
df.head()

,Unnamed: 0,iniciales,Persona,Correo,Permisos,Entidad,Area,Tablero,Url
0,0,OJ,Oscar Javier Pachon Alvarez,oscar.pachon@AvalDigitalLabs.com,"Workspace Member, All permissions granted",BPOP,adl-gb-general-prod,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
1,1,MM,Monica Marcela Carvajal Cruz,monica.carvajal@AvalDigitalLabs.com,"Workspace Admin, All permissions granted",BPOP,adl-gb-general-prod,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
2,2,DP,David Pierre Rodriguez Quiroga,pierre.rodriguez@AvalDigitalLabs.com,"Workspace Member, All permissions granted",BPOP,adl-gb-general-prod,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
3,3,CC,Cristian Camilo Velandia Cardenas,cristian.velandia@AvalDigitalLabs.com,"Workspace Member, All permissions granted",BPOP,adl-gb-general-prod,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
4,4,LN,Leidi Natalia Garzon Ramirez,leidi.garzon@AvalDigitalLabs.com,"Workspace Member, All permissions granted",BPOP,adl-gb-general-prod,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...

In [56]:
df_t = df[(df["Permisos"] == "Read") & (~df["Correo"].str.contains("@AvalDigitalLabs.com", regex = False))].drop(["Unnamed: 0", "iniciales", "Area", "Entidad"], axis = 1).drop_duplicates()
df_t["Url"] = df_t["Url"].str.replace("/permission/report/2", "/reports").str.replace("/directAccess?experience=power-bi", "/ReportSection?experience=power-bi")

In [57]:
df_t.head()

,Persona,Correo,Permisos,Tablero,Url
12,CLAUDIA FIGUEROA CORDERO,55302892_bancopopular.com.co#EXT#@graval.onmic...,Read,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
13,ANGIE DAYANNA HERNANDEZ ORJUELA,1018508242@bancopopular.com.co,Read,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
14,DANIEL AVILA SANDOVAL,1000320478@bancopopular.com.co,Read,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
15,MIGUEL ANGEL MORANTES GOMEZ,1031181590@bancopopular.com.co,Read,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...
16,JESIKA JASMIN ROMERO VELANDIA,jesika_romero@bancopopular.com.co,Read,adl-bpop-Visual-Log_HabeasData,https://app.powerbi.com/groups/1efd6918-0f29-...

In [58]:
df_t.shape

(640, 5)

In [59]:
df_t.to_excel("reporte accesos a tableros bpop {0}.xlsx".format(str(date.today())), index=False)

In [60]:
df_t["Tablero"].value_counts()

Tablero
 Seguimiento Presta Ya Digital Libranzas Popular    158
 Seguimiento Tarjeta de Crédito Popular              86
 Seguimiento Libranzas Popular Digital               58
 Seguimiento Cuenta de Ahorros Popular               51
 Fraude_GreenBank                                    36
 Seguimiento CDT digital                             35
 adl-bpop-hipotecario-visual                         35
 Control de Proceso TC Digital - Popular             33
 GB_Log_Seguridad_Fraude                             28
 Seguimiento Regionales Popular                      24
 GB_Responsys_CasoUso_Aumento_TC                     18
 adl-bpop-visual-seguimiento_canales                 12
 Control Fabrica Libranzas Popular                   10
 adl-bpop-Visual-Log_HabeasData                       9
 GB_Visual_Libranzas_ConsultaAsegurabilidad           7
 adl-bpop-viz-crm-segmentacion                        6
 GB_Libranzas_Soporte                                 5
 adl-bpop-libranza-consulta_para_pagare-viz           5
 adl-bpop-hipotecario_soporte-visual                  5
 adl-bpop-visual-trv-onboarding_uso                   4
 adl-bpop-Visual-Responsys_Log_Seguridad              4
 GB_TC_Seguimiento_Fallos                             4
 adl-bpop-visual-Libranzas-Desborde_a_Desembolso      4
 adl-bpop-fomento-visual                              3
Name: count, dtype: int64